service: lambda-todo-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
  httpApi:
    cors: true

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0

functions:
  listTodos:
    handler: src/handlers/todos/list.handler
    events:
      - httpApi:
          path: /todos
          method: get

  createTodo:
    handler: src/handlers/todos/create.handler
    events:
      - httpApi:
          path: /todos
          method: post

  updateTodo:
    handler: src/handlers/todos/update.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: put

  deleteTodo:
    handler: src/handlers/todos/delete.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: delete
