services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - frontend_node_modules:/workspace/frontend/node_modules
      - backend_node_modules:/workspace/backend/node_modules
      - e2e_node_modules:/workspace/e2e/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"

volumes:
  node_modules:
  frontend_node_modules:
  backend_node_modules:
  e2e_node_modules: